version: '2.3'

checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 100
  identical-code:
    config:
      threshold: 50

exclude_patterns:
  - 'dist/'
  - 'node_modules/'
  - '**/*.min.js'
  - '**/*.bundle.js'
  - '**/vendor/'
  - '**/test/'
  - '**/tests/'
  - '**/spec/'
  - '**/__tests__/'
  - '**/__mocks__/'
  - '**/coverage/'
  - '**/public/'
  - '**/build/'
  - '**/dist/'
  - '**/*.config.js'
  - '**/webpack.config.js'
  - '**/gulpfile.js'
  - '**/Gruntfile.js'
  - '**/karma.conf.js'
  - '**/jest.config.js'
  - '**/cypress/'
  - '**/cypress.config.js'
  - '**/cypress.env.json'
  - '**/cypress.env.example.json'
