# Estágio de testes
FROM node:18-alpine

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de definição de dependências
COPY package*.json ./

# Instala as dependências incluindo as de desenvolvimento
RUN npm install

# Copia o restante dos arquivos do projeto
COPY . .

# Comando para executar os testes
CMD ["npm", "test"]
